services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - streaming-db-data:/var/lib/postgresql/data

  rtmp:
    build: ./apps/rtmp-server
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./hls:/var/www/html/hls
    networks:
      - appnet

networks:
  appnet:
    driver: bridge  
volumes:
  streaming-db-data: