listen              1935;
max_connections     1000;

daemon              off;
srs_log_tank        console;

http_server {
    enabled         on;
    listen          8080;
}

http_api {
    enabled         on;
    listen          1985;
}

vhost __defaultVhost__ {
    rtc {
        enabled     off;
    }

    hls {
        enabled         on;
        hls_fragment    1;
        hls_window      4;
        hls_wait_keyframe off;
        hls_path        ./objs/nginx/html;
    }

    http_hooks {
        enabled         on;
        on_publish      http://backend:3000/stream/start;
        on_unpublish    http://backend:3000/stream/end;
    }
}
